version: '3.8'

services:
  web:
    build: .
    command: gunicorn --chdir TaskManager --bind 0.0.0.0:8000 TaskManager.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=TaskManager.settings