services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_taskmanager
    command: gunicorn --chdir TaskManager --bind 0.0.0.0:8000 TaskManager.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DOCKERIZED=1  # Добавлено здесь
    depends_on:
      - redis
      - mailhog
      - celery-worker
      - celery-beat

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Веб-интерфейс
      - "1025:1025"  # SMTP-сервер

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A TaskManager worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DOCKERIZED=1  # Добавлено здесь
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A TaskManager beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DOCKERIZED=1  # Добавлено здесь
    depends_on:
      - redis
